name: Run Pester Tests for Azure

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull request to the main branch

jobs:
  run-pester-tests:
    runs-on: windows-latest  # Use a Windows runner to run PowerShell scripts

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install PowerShell Core if not already available
      - name: Install PowerShell (if needed)
        shell: bash
        run: |
          if (-not (Get-Command pwsh -ErrorAction SilentlyContinue)) {
            Write-Host "Installing PowerShell Core"
            Invoke-WebRequest -Uri https://aka.ms/install-powershell.ps1 -OutFile install-powershell.ps1
            pwsh -File install-powershell.ps1
          }
        
      # Install the latest version of Pester module
      - name: Install Pester
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck -Scope CurrentUser

      # Run the Pester tests
      - name: Run Pester Tests
        run: |
          # Run all Pester tests in the current directory (adjust path as needed)
          Invoke-Pester -Path ./tests  # Make sure you update the path to where your tests are located
