name: Run Pester Tests for Azure

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull request to main branch

jobs:
  run-pester-tests:
    runs-on: windows-latest  # Use a Windows runner to run PowerShell scripts

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PowerShell
      - name: Set up PowerShell
        uses: actions/setup-powershell@v2

      # Install the latest version of Pester module
      - name: Install Pester
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck -Scope CurrentUser
      # Update the latest version of Pester module
      - name: Update Pester
        run: |
          Update-Module -Name Pester
          
      # # Run the Pester tests
      # - name: Run Pester Tests
      #   run: |
      #     # Run all Pester tests in the current directory (adjust path as needed)
      #     Invoke-Pester -Path ./tests  # Make sure you update the path to where your tests are located
